packages:
  - apps/*
  - packages/*
overrides:
  tmp: 0.2.6
  '@xmldom/xmldom@<0.8.13': '>=0.8.13'
  brace-expansion@<1.1.13: 1.1.14
  brace-expansion@>=4.0.0 <5.0.5: 5.0.6
  brace-expansion@>=5.0.0 <5.0.6: 5.0.6
  ip-address@<=10.1.0: '>=10.1.1'
  next@>=16.0.0 <16.2.5: '>=16.2.5'
  next@>=16.0.0 <16.2.6: '>=16.2.6'
  next@>=16.0.0-beta.0 <16.2.3: '>=16.2.3'
  picomatch@>=4.0.0 <4.0.4: 4.0.4
  postcss@<8.5.10: '>=8.5.10'
