// State lookup contract

export const STATE_NAME_TO_CODE = new Map<string, string>([
  ["alabama", "AL"],
  ["alaska", "AK"],
  ["arizona", "AZ"],
  ["arkansas", "AR"],
  ["california", "CA"],
  ["colorado", "CO"],
  ["connecticut", "CT"],
  ["delaware", "DE"],
  ["district of columbia", "DC"],
  ["florida", "FL"],
  ["georgia", "GA"],
  ["hawaii", "HI"],
  ["idaho", "ID"],
  ["illinois", "IL"],
  ["indiana", "IN"],
  ["iowa", "IA"],
  ["kansas", "KS"],
  ["kentucky", "KY"],
  ["louisiana", "LA"],
  ["maine", "ME"],
  ["maryland", "MD"],
  ["massachusetts", "MA"],
  ["michigan", "MI"],
  ["minnesota", "MN"],
  ["mississippi", "MS"],
  ["missouri", "MO"],
  ["montana", "MT"],
  ["nebraska", "NE"],
  ["nevada", "NV"],
  ["new hampshire", "NH"],
  ["new jersey", "NJ"],
  ["new mexico", "NM"],
  ["new york", "NY"],
  ["north carolina", "NC"],
  ["north dakota", "ND"],
  ["ohio", "OH"],
  ["oklahoma", "OK"],
  ["oregon", "OR"],
  ["pennsylvania", "PA"],
  ["rhode island", "RI"],
  ["south carolina", "SC"],
  ["south dakota", "SD"],
  ["tennessee", "TN"],
  ["texas", "TX"],
  ["utah", "UT"],
  ["vermont", "VT"],
  ["virginia", "VA"],
  ["washington", "WA"],
  ["west virginia", "WV"],
  ["wisconsin", "WI"],
  ["wyoming", "WY"]
]);

// North Carolina location boundary

const NORTH_CAROLINA_CITY_STATE_SUGGESTIONS = [
  "Aberdeen, NC",
  "Advance, NC",
  "Albemarle, NC",
  "Angier, NC",
  "Apex, NC",
  "Archdale, NC",
  "Arden, NC",
  "Asheboro, NC",
  "Asheville, NC",
  "Atlantic Beach, NC",
  "Ayden, NC",
  "Banner Elk, NC",
  "Beaufort, NC",
  "Belmont, NC",
  "Benson, NC",
  "Black Mountain, NC",
  "Blowing Rock, NC",
  "Boone, NC",
  "Brevard, NC",
  "Bryson City, NC",
  "Burlington, NC",
  "Calabash, NC",
  "Canton, NC",
  "Carrboro, NC",
  "Cary, NC",
  "Chapel Hill, NC",
  "Charlotte, NC",
  "China Grove, NC",
  "Clayton, NC",
  "Clemmons, NC",
  "Clinton, NC",
  "Concord, NC",
  "Cornelius, NC",
  "Davidson, NC",
  "Denver, NC",
  "Durham, NC",
  "Dunn, NC",
  "Eden, NC",
  "Edenton, NC",
  "Elizabeth City, NC",
  "Elkin, NC",
  "Elon, NC",
  "Emerald Isle, NC",
  "Fairview, NC",
  "Fayetteville, NC",
  "Farmville, NC",
  "Fletcher, NC",
  "Forest City, NC",
  "Franklin, NC",
  "Fuquay-Varina, NC",
  "Garner, NC",
  "Gastonia, NC",
  "Goldsboro, NC",
  "Graham, NC",
  "Greensboro, NC",
  "Greenville, NC",
  "Hamlet, NC",
  "Hampstead, NC",
  "Havelock, NC",
  "Henderson, NC",
  "Hendersonville, NC",
  "Hickory, NC",
  "High Point, NC",
  "Hillsborough, NC",
  "Holly Ridge, NC",
  "Holly Springs, NC",
  "Hope Mills, NC",
  "Huntersville, NC",
  "Indian Trail, NC",
  "Jacksonville, NC",
  "Jamestown, NC",
  "Kannapolis, NC",
  "Kernersville, NC",
  "Kinston, NC",
  "Kill Devil Hills, NC",
  "Kings Mountain, NC",
  "Knightdale, NC",
  "Lake Norman of Catawba, NC",
  "Laurinburg, NC",
  "Leland, NC",
  "Lewisville, NC",
  "Lexington, NC",
  "Lincolnton, NC",
  "Locust, NC",
  "Louisburg, NC",
  "Lumberton, NC",
  "Maiden, NC",
  "Marion, NC",
  "Marshville, NC",
  "Matthews, NC",
  "Mebane, NC",
  "Mint Hill, NC",
  "Mocksville, NC",
  "Monroe, NC",
  "Mooresville, NC",
  "Morehead City, NC",
  "Morganton, NC",
  "Morrisville, NC",
  "Mount Airy, NC",
  "Mount Holly, NC",
  "Nags Head, NC",
  "New Bern, NC",
  "Newton, NC",
  "Oak Island, NC",
  "Oak Ridge, NC",
  "Oxford, NC",
  "Pinehurst, NC",
  "Pineville, NC",
  "Pittsboro, NC",
  "Raleigh, NC",
  "Randleman, NC",
  "Reidsville, NC",
  "Roanoke Rapids, NC",
  "Rocky Mount, NC",
  "Rolesville, NC",
  "Roxboro, NC",
  "Salisbury, NC",
  "Sanford, NC",
  "Selma, NC",
  "Shallotte, NC",
  "Shelby, NC",
  "Smithfield, NC",
  "Sneads Ferry, NC",
  "Southport, NC",
  "Southern Pines, NC",
  "Spring Lake, NC",
  "Stallings, NC",
  "Statesville, NC",
  "Summerfield, NC",
  "Swansboro, NC",
  "Sylva, NC",
  "Taylorsville, NC",
  "Thomasville, NC",
  "Trinity, NC",
  "Tryon, NC",
  "Wake Forest, NC",
  "Wallace, NC",
  "Waxhaw, NC",
  "Waynesville, NC",
  "Weaverville, NC",
  "Wendell, NC",
  "West Jefferson, NC",
  "Whiteville, NC",
  "Wilkesboro, NC",
  "Wilmington, NC",
  "Wilson, NC",
  "Winterville, NC",
  "Winston-Salem, NC",
  "Wrightsville Beach, NC",
  "Yadkinville, NC",
  "Youngsville, NC",
  "Zebulon, NC"
] as const;

// National location boundary

const MAJOR_US_CITY_STATE_SUGGESTIONS = [
  "Akron, OH",
  "Albuquerque, NM",
  "Anaheim, CA",
  "Anchorage, AK",
  "Arlington, VA",
  "Arlington, TX",
  "Amarillo, TX",
  "Atlanta, GA",
  "Augusta, GA",
  "Aurora, CO",
  "Austin, TX",
  "Bakersfield, CA",
  "Baltimore, MD",
  "Baton Rouge, LA",
  "Birmingham, AL",
  "Boise, ID",
  "Boston, MA",
  "Buffalo, NY",
  "Charleston, SC",
  "Charleston, WV",
  "Chandler, AZ",
  "Chattanooga, TN",
  "Chesapeake, VA",
  "Chicago, IL",
  "Chula Vista, CA",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Colorado Springs, CO",
  "Columbia, SC",
  "Columbus, OH",
  "Corpus Christi, TX",
  "Dallas, TX",
  "Dayton, OH",
  "Denver, CO",
  "Des Moines, IA",
  "Detroit, MI",
  "El Paso, TX",
  "Eugene, OR",
  "Fort Lauderdale, FL",
  "Fort Wayne, IN",
  "Fort Worth, TX",
  "Frisco, TX",
  "Fresno, CA",
  "Garland, TX",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Grand Rapids, MI",
  "Greenville, SC",
  "Henderson, NV",
  "Hialeah, FL",
  "Honolulu, HI",
  "Houston, TX",
  "Huntington Beach, CA",
  "Indianapolis, IN",
  "Irvine, CA",
  "Jackson, MS",
  "Jacksonville, FL",
  "Jersey City, NJ",
  "Kansas City, MO",
  "Knoxville, TN",
  "Las Vegas, NV",
  "Lexington, KY",
  "Lincoln, NE",
  "Little Rock, AR",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Louisville, KY",
  "Lubbock, TX",
  "Madison, WI",
  "Memphis, TN",
  "Mesa, AZ",
  "Miami, FL",
  "Milpitas, CA",
  "Milwaukee, WI",
  "Minneapolis, MN",
  "Mobile, AL",
  "Modesto, CA",
  "Napa, CA",
  "Nashville, TN",
  "New Haven, CT",
  "New Orleans, LA",
  "New York, NY",
  "Newark, NJ",
  "Newport News, VA",
  "Norfolk, VA",
  "North Las Vegas, NV",
  "Oakland, CA",
  "Oklahoma City, OK",
  "Omaha, NE",
  "Orlando, FL",
  "Pasadena, CA",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pittsburgh, PA",
  "Plano, TX",
  "Portland, OR",
  "Providence, RI",
  "Reno, NV",
  "Richmond, VA",
  "Riverside, CA",
  "Rochester, NY",
  "Sacramento, CA",
  "Saint Petersburg, FL",
  "Saint Louis, MO",
  "Saint Paul, MN",
  "Salem, OR",
  "Salt Lake City, UT",
  "San Antonio, TX",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Santa Ana, CA",
  "Santa Clarita, CA",
  "Savannah, GA",
  "Scottsdale, AZ",
  "Seattle, WA",
  "Spokane, WA",
  "Stamford, CT",
  "Stockton, CA",
  "Tacoma, WA",
  "Tallahassee, FL",
  "Tampa, FL",
  "Tempe, AZ",
  "Toledo, OH",
  "Tucson, AZ",
  "Tulsa, OK",
  "Vancouver, WA",
  "Virginia Beach, VA",
  "Washington, DC",
  "Wichita, KS",
  "Worcester, MA",
  "Yonkers, NY"
] as const;

// Suggestion merge boundary

export const SCOUT_CITY_STATE_SUGGESTIONS = [
  ...new Set([
    ...NORTH_CAROLINA_CITY_STATE_SUGGESTIONS,
    ...MAJOR_US_CITY_STATE_SUGGESTIONS
  ])
];
